redis:
  image: redis
  restart: always 
  container_name: myrediscompose
  ports:
    - "6379:6379"
mysql:
  image: mysql
  restart: always
  container_name: mysqlserver
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root@password

